### ISSUE TITLE
[libgit2] Getting errors for undefined symbol: git_commit_id

### ISSUE THREAD

**Issue by vnykmshr** [TooTallNate/n8.io-old#11]
Hi Nate,

I am getting errors for undefined `git_commit_id`, `git_reference_oid`, `git_tree_entry_attributes`, `git_tree_get_subtree`. I have installed libgit2 latest from their `development` branch. 

I am running my blog based on n8.io at vnykmshr.com.

Can you help me resolve these issues?

**Comment by TooTallNate** [comment]
Can you show me the full error you're seeing? FWIW I'm using `libgit2.so.0.17.0` (so v0.17.0). It probably not the newest version of libgit2 by now.

**Comment by vnykmshr** [comment]
I get the following error when I fire up the server. If I comment reference to `git_commit_id` out, I get similar error for other symbols. I understand these symbols are no longer exported, no idea why. I am still running `v0.17.0` in production, but was trying a fresh build on local from the latest code (`v0.18.0`, I think).

```
$ node server.js 

/home/vm/workspace/vm/node_modules/ffi/lib/dynamic_library.js:112
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error())
          ^
Error: Dynamic Symbol Retrieval Error: /usr/local/lib/libgit2.so: undefined symbol: git_commit_id
    at DynamicLibrary.get (/home/vm/workspace/vm/node_modules/ffi/lib/dynamic_library.js:112:11)
    at /home/vm/workspace/vm/node_modules/ffi/lib/library.js:50:19
    at Array.forEach (native)
    at Object.Library (/home/vm/workspace/vm/node_modules/ffi/lib/library.js:47:28)
    at Object.<anonymous> (/home/vm/workspace/vm/lib/git.js:59:5)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```

**Comment by vnykmshr** [comment]
`git_commit_id` is exported now, according to changelog of `v0.18.0` from this comment (https://github.com/libgit2/libgit2/issues/1336#issuecomment-16206447), among many symbols replaced/removed, these are the ones that concern me;
- `git_reference_oid` -> `git_reference_target`
- `git_tree_entry_attributes` -> `git_tree_entry_filemode`
- `git_tree_get_subtree` -> `git_tree_entry_bypath`

I attempted to export `git_reference_oid` in `git.js`;

```
// git_reference_oid: [git_oid_ptr, [git_reference]],
exports.git_reference_oid = function (id, git_reference) {
  return exports.git_reference_target(id, git_reference);
};
```

The above does not work as number of expected args do not match. I tried other combinations but no luck. Can you please help me with this?

**Comment by vnykmshr** [comment]
Guess I will close the issue as it seems like something I will have to find a way out myself. Thanks for your time.
